# Nombre de la aplicación
spring.application.name=torneo-api

# Configuración de conexión a MySQL (ajustá según tu base)
spring.datasource.url=jdbc:mysql://localhost:3306/torneo_db
spring.datasource.username=root
spring.datasource.password=French4932

# Dialecto de Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mostrar las consultas SQL en consola
spring.jpa.show-sql=true

# Actualizar automáticamente las tablas según las entidades
spring.jpa.hibernate.ddl-auto=update

# Puerto (opcional, por defecto 8080)
server.port=8080
